// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: replication/replicator.proto

//protoc --go_out=. --go-grpc_out=. replication/replicator.proto

package replicator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Replicator_BeginReplication_FullMethodName = "/replication.Replicator/BeginReplication"
	Replicator_DebugWrite_FullMethodName       = "/replication.Replicator/DebugWrite"
)

// ReplicatorClient is the client API for Replicator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicatorClient interface {
	BeginReplication(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Entries], error)
	DebugWrite(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
}

type replicatorClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicatorClient(cc grpc.ClientConnInterface) ReplicatorClient {
	return &replicatorClient{cc}
}

func (c *replicatorClient) BeginReplication(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Entries], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Replicator_ServiceDesc.Streams[0], Replicator_BeginReplication_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BeginRequest, Entries]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replicator_BeginReplicationClient = grpc.ServerStreamingClient[Entries]

func (c *replicatorClient) DebugWrite(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, Replicator_DebugWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicatorServer is the server API for Replicator service.
// All implementations must embed UnimplementedReplicatorServer
// for forward compatibility.
type ReplicatorServer interface {
	BeginReplication(*BeginRequest, grpc.ServerStreamingServer[Entries]) error
	DebugWrite(context.Context, *WriteRequest) (*WriteResponse, error)
	mustEmbedUnimplementedReplicatorServer()
}

// UnimplementedReplicatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicatorServer struct{}

func (UnimplementedReplicatorServer) BeginReplication(*BeginRequest, grpc.ServerStreamingServer[Entries]) error {
	return status.Errorf(codes.Unimplemented, "method BeginReplication not implemented")
}
func (UnimplementedReplicatorServer) DebugWrite(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DebugWrite not implemented")
}
func (UnimplementedReplicatorServer) mustEmbedUnimplementedReplicatorServer() {}
func (UnimplementedReplicatorServer) testEmbeddedByValue()                    {}

// UnsafeReplicatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicatorServer will
// result in compilation errors.
type UnsafeReplicatorServer interface {
	mustEmbedUnimplementedReplicatorServer()
}

func RegisterReplicatorServer(s grpc.ServiceRegistrar, srv ReplicatorServer) {
	// If the following call pancis, it indicates UnimplementedReplicatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Replicator_ServiceDesc, srv)
}

func _Replicator_BeginReplication_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BeginRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicatorServer).BeginReplication(m, &grpc.GenericServerStream[BeginRequest, Entries]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replicator_BeginReplicationServer = grpc.ServerStreamingServer[Entries]

func _Replicator_DebugWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServer).DebugWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replicator_DebugWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServer).DebugWrite(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Replicator_ServiceDesc is the grpc.ServiceDesc for Replicator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Replicator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replication.Replicator",
	HandlerType: (*ReplicatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DebugWrite",
			Handler:    _Replicator_DebugWrite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BeginReplication",
			Handler:       _Replicator_BeginReplication_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "replication/replicator.proto",
}
