// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: replication/replicator.proto

//protoc --go_out=. --go-grpc_out=. replication/replicator.proto

package replicator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LastIndex       uint64                 `protobuf:"varint,1,opt,name=lastIndex,proto3" json:"lastIndex,omitempty"`
	FilteredStreams []string               `protobuf:"bytes,2,rep,name=filteredStreams,proto3" json:"filteredStreams,omitempty"`
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BeginRequest) Reset() {
	*x = BeginRequest{}
	mi := &file_replication_replicator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRequest) ProtoMessage() {}

func (x *BeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_replicator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRequest.ProtoReflect.Descriptor instead.
func (*BeginRequest) Descriptor() ([]byte, []int) {
	return file_replication_replicator_proto_rawDescGZIP(), []int{0}
}

func (x *BeginRequest) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

func (x *BeginRequest) GetFilteredStreams() []string {
	if x != nil {
		return x.FilteredStreams
	}
	return nil
}

func (x *BeginRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_replication_replicator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_replication_replicator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_replication_replicator_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type Entries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entries) Reset() {
	*x = Entries{}
	mi := &file_replication_replicator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entries) ProtoMessage() {}

func (x *Entries) ProtoReflect() protoreflect.Message {
	mi := &file_replication_replicator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entries.ProtoReflect.Descriptor instead.
func (*Entries) Descriptor() ([]byte, []int) {
	return file_replication_replicator_proto_rawDescGZIP(), []int{2}
}

func (x *Entries) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_replication_replicator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_replicator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_replication_replicator_proto_rawDescGZIP(), []int{3}
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_replication_replicator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_replicator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_replication_replicator_proto_rawDescGZIP(), []int{4}
}

func (x *WriteResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_replication_replicator_proto protoreflect.FileDescriptor

const file_replication_replicator_proto_rawDesc = "" +
	"\n" +
	"\x1creplication/replicator.proto\x12\vreplication\"l\n" +
	"\fBeginRequest\x12\x1c\n" +
	"\tlastIndex\x18\x01 \x01(\x04R\tlastIndex\x12(\n" +
	"\x0ffilteredStreams\x18\x02 \x03(\tR\x0ffilteredStreams\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"1\n" +
	"\x05Entry\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"7\n" +
	"\aEntries\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.replication.EntryR\aentries\"\"\n" +
	"\fWriteRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"%\n" +
	"\rWriteResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index2\x98\x01\n" +
	"\n" +
	"Replicator\x12E\n" +
	"\x10BeginReplication\x12\x19.replication.BeginRequest\x1a\x14.replication.Entries0\x01\x12C\n" +
	"\n" +
	"DebugWrite\x12\x19.replication.WriteRequest\x1a\x1a.replication.WriteResponseB\x19Z\x17/replication/replicatorb\x06proto3"

var (
	file_replication_replicator_proto_rawDescOnce sync.Once
	file_replication_replicator_proto_rawDescData []byte
)

func file_replication_replicator_proto_rawDescGZIP() []byte {
	file_replication_replicator_proto_rawDescOnce.Do(func() {
		file_replication_replicator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replication_replicator_proto_rawDesc), len(file_replication_replicator_proto_rawDesc)))
	})
	return file_replication_replicator_proto_rawDescData
}

var file_replication_replicator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_replication_replicator_proto_goTypes = []any{
	(*BeginRequest)(nil),  // 0: replication.BeginRequest
	(*Entry)(nil),         // 1: replication.Entry
	(*Entries)(nil),       // 2: replication.Entries
	(*WriteRequest)(nil),  // 3: replication.WriteRequest
	(*WriteResponse)(nil), // 4: replication.WriteResponse
}
var file_replication_replicator_proto_depIdxs = []int32{
	1, // 0: replication.Entries.entries:type_name -> replication.Entry
	0, // 1: replication.Replicator.BeginReplication:input_type -> replication.BeginRequest
	3, // 2: replication.Replicator.DebugWrite:input_type -> replication.WriteRequest
	2, // 3: replication.Replicator.BeginReplication:output_type -> replication.Entries
	4, // 4: replication.Replicator.DebugWrite:output_type -> replication.WriteResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_replication_replicator_proto_init() }
func file_replication_replicator_proto_init() {
	if File_replication_replicator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replication_replicator_proto_rawDesc), len(file_replication_replicator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replication_replicator_proto_goTypes,
		DependencyIndexes: file_replication_replicator_proto_depIdxs,
		MessageInfos:      file_replication_replicator_proto_msgTypes,
	}.Build()
	File_replication_replicator_proto = out.File
	file_replication_replicator_proto_goTypes = nil
	file_replication_replicator_proto_depIdxs = nil
}
